# Generated by Django 5.2.4 on 2025-07-19 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='lease_duration_months',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='property',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='title',
        ),
        migrations.AddField(
            model_name='lease',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.city'),
        ),
        migrations.AddField(
            model_name='lease',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.location'),
        ),
        migrations.AddField(
            model_name='lease',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='LeaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leases/')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.lease')),
            ],
        ),
    ]
