# Generated by Django 5.2.4 on 2025-08-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newProject',
        ),
    ]
