# Generated by Django 5.2.4 on 2025-07-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_lease_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='posted_on',
        ),
        migrations.AddField(
            model_name='lease',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
