# Generated by Django 5.2.4 on 2025-08-24 10:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_contact_email_alter_leadrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='brochure',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
    ]
