# Generated by Django 5.2.4 on 2025-08-25 05:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_newproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='newproject',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='brochure',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='brochure'),
        ),
    ]
