# Generated by Django 5.2.4 on 2025-08-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_newproject_brochure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newProject',
        ),
    ]
