# Generated by Django 5.2.4 on 2025-07-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_lease_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='my_app.property'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.city'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.location'),
        ),
    ]
