# Generated by Django 5.2.4 on 2025-07-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.city'),
        ),
    ]
