# Generated by Django 5.2.4 on 2025-08-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_name_newproject_title_newproject_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='contact_name',
            new_name='agent_name',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='owner_user',
        ),
    ]
