# Generated by Django 5.2.4 on 2025-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_contact_name_lease_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='brochure',
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
