# Generated by Django 5.2.4 on 2025-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_lease_property_alter_lease_city_alter_lease_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
