# Generated by Django 5.2.4 on 2025-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_newproject_remove_location_location_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='project_description',
            field=models.CharField(blank=True, null=True, verbose_name=500),
        ),
        migrations.AddField(
            model_name='newproject',
            name='project_title',
            field=models.CharField(blank=True, null=True, verbose_name=200),
        ),
    ]
