# Generated by Django 5.2.4 on 2025-07-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_lease_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.city')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='SellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sell_images/')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.sell')),
            ],
        ),
    ]
