# Generated by Django 5.2.4 on 2025-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_newproject_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproject',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='newproject',
            name='project_title',
        ),
        migrations.AddField(
            model_name='newproject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='newProject/pdfs'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newproject',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
