# Generated by Django 5.2.4 on 2025-07-22 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_lease_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.purpose'),
        ),
    ]
