# Generated by Django 5.2.4 on 2025-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysearch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertysearch',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='propertysearch',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='PropertySearch',
        ),
    ]
