# Generated by Django 5.2.4 on 2025-07-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
