# Generated by Django 5.2.4 on 2025-07-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_remove_sell_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
