# Generated by Django 5.2.4 on 2025-07-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_sell_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseimage',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='sellimage',
            name='sell',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='LeaseImage',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='SellImage',
        ),
    ]
