# Generated by Django 5.2.4 on 2025-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_remove_leaseimage_lease_remove_sell_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
