# Generated by Django 5.2.4 on 2025-07-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_property_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='author',
            new_name='Posted_by',
        ),
    ]
