# Generated by Django 5.2.4 on 2025-07-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_rename_author_property_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Posted_by',
            new_name='posted_by',
        ),
        migrations.AddField(
            model_name='property',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='property/brochures/'),
        ),
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='my_app.property')),
            ],
        ),
    ]
