# Generated by Django 5.2.4 on 2025-07-23 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_property_terms_and_conditions_lease_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lease',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
