# Generated by Django 5.2.4 on 2025-07-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_remove_lease_created_at_remove_lease_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.propertytype'),
        ),
    ]
