# Generated by Django 5.2.4 on 2025-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_property_agent_phone_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
