# Generated by Django 5.2.4 on 2025-07-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_leadrequest_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
