# Generated by Django 5.2.4 on 2025-07-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_lease_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseimage',
            name='lease',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='LeaseImage',
        ),
    ]
