# Generated by Django 5.2.4 on 2025-07-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_property_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
    ]
