# Generated by Django 5.2.4 on 2025-07-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_lease_leaseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.propertytype'),
        ),
        migrations.AddField(
            model_name='lease',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
