# Generated by Django 5.2.4 on 2025-07-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_lease_property_type_lease_terms_and_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='contact_name',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='property',
        ),
    ]
