# Generated by Django 5.2.4 on 2025-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_lease_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
