# Generated by Django 5.2.4 on 2025-07-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_lease_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseimage',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(),
        ),
    ]
