# Generated by Django 5.2.4 on 2025-07-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseimage',
            name='image',
            field=models.ImageField(upload_to='leases/'),
        ),
    ]
