# Generated by Django 5.2.4 on 2025-07-25 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_alter_leaseimage_image_alter_newproject_brochure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='brochure',
            field=cloudinary.models.CloudinaryField(default=111, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newproject',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='brochure',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
