# Generated by Django 5.2.4 on 2025-07-26 04:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_alter_newproject_brochure_alter_property_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='brochure',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_brochures/'),
        ),
    ]
