# Generated by Django 5.2.4 on 2025-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_alter_newproject_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproject',
            name='brochure',
        ),
        migrations.AddField(
            model_name='newproject',
            name='brochure_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
