# Generated by Django 5.2.4 on 2025-08-01 03:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproject',
            name='brochure_url',
        ),
        migrations.AddField(
            model_name='newproject',
            name='brochure',
            field=models.FileField(default=1, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_brochures/'),
            preserve_default=False,
        ),
    ]
